### ISSUE TITLE
[ERROR]: (node:1632) UnhandledPromiseRejectionWarning: RangeError: RichEmbed field values may not be empty.

### ISSUE THREAD

**Issue by DeathKillerNOR** [The-SourceCode/Discord.js-Bot-Development#18]
Index.js in .txt arrached.

Using this code i'm getting a error when trying to for example kick another user:

(node:1632) UnhandledPromiseRejectionWarning: RangeError: RichEmbed field values may not be empty.
    at RichEmbed.addField (E:\#DeathKillerNOR Discord Bots\DeathKillerBot\node_modules\discord.js\src\structures\RichEmbed.js:165:34)
    at Client.bot.on (E:\#DeathKillerNOR Discord Bots\DeathKillerBot\index.js:86:6)
    at Client.emit (events.js:187:15)
    at MessageCreateHandler.handle (E:\#DeathKillerNOR Discord Bots\DeathKillerBot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (E:\#DeathKillerNOR Discord Bots\DeathKillerBot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (E:\#DeathKillerNOR Discord Bots\DeathKillerBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (E:\#DeathKillerNOR Discord Bots\DeathKillerBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (E:\#DeathKillerNOR Discord Bots\DeathKillerBot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (E:\#DeathKillerNOR Discord Bots\DeathKillerBot\node_modules\ws\lib\websocket.js:137:47)
(node:1632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by
throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[index.txt](https://github.com/The-SourceCode/Discord.js-Bot-Development/files/2775798/index.txt)

**Comment by DeathKillerNOR** [comment]
never mind, when you try to kick without using a "reason" it will give you this error. Took me way to long to figure that out.

**Comment by sonicrules11** [comment]
```
if(!kUser) return message.channel.send({embed: {
    color: Math.floor(Math.random() * 16777214) + 1,
    description: "`[yourprefixhere]kick @User Reason`"
}});
```
If you wanna avoid that error in command prompt/terminal use this

**Comment by DeathKillerNOR** [comment]
oh, that makes sense.
Thanks for the reply :)

**Comment by Neeef** [comment]
Could just use `if(!kReason) kReason = "None";` if you don't want to cancel the function. You can close the issue btw.
