### ISSUE TITLE
Fortnite command just won't work ;-;

### ISSUE THREAD

**Issue by DuyGaming** [The-SourceCode/Discord.js-Bot-Development#33]
**PS C:\Users\AsrieltheGoat\Desktop\bot> node index.js
.---------------------------.
|         Commands          |
|---------------------------|
|   Command   | Load status |
|-------------|-------------|
| fortnite.js | OK          |
| hmm.js      | OK          |
| love.js     | OK          |
| meme.js     | OK          |
| rps.js      | OK          |
| help.js     | OK          |
| info.js     | OK          |
| ping.js     | OK          |
| whois.js    | OK          |
| ban.js      | OK          |
| clear.js    | OK          |
| kick.js     | OK          |
| report.js   | OK          |
| say.js      | OK          |
'---------------------------'
Hi, A********* is now online!
(node:6532) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.run (C:\Users\AsrieltheGoat\Desktop\bot\commands\experiment\fortnite.js:19:21)
    at Client.<anonymous> (C:\Users\AsrieltheGoat\Desktop\bot\index.js:51:17)
    at Client.emit (events.js:210:5)
    at MessageCreateHandler.handle (C:\Users\AsrieltheGoat\Desktop\bot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\AsrieltheGoat\Desktop\bot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\AsrieltheGoat\Desktop\bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\AsrieltheGoat\Desktop\bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\AsrieltheGoat\Desktop\bot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:210:5)
    at Receiver.receiverOnMessage (C:\Users\AsrieltheGoat\Desktop\bot\node_modules\ws\lib\websocket.js:789:20)
(node:6532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

Here the error message 
I think there is something wrong with ur code ;-;
I spend a day to troubleshooting ur code but nothing change ;-;

**Comment by zientix** [comment]
Are u typing only the command or command with an argument
