### ISSUE TITLE
Kick and Ban command not working

### ISSUE THREAD

**Issue by husnainjatoi0** [The-SourceCode/Discord.js-Bot-Development#34]
Kick and Ban commands are not working when we use kick or ban command the console says : 
**(node:72728) UnhandledPromiseRejectionWarning: TypeError: promptMessage is not a function
    at C:\Users\Husnain-Ayesha jatoi\Desktop\Nain Bot\commands\Moderators\kick.js:76:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.run (C:\Users\Husnain-Ayesha jatoi\Desktop\Nain Bot\commands\Moderators\kick.js:74:9)
(node:72728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:72728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**   Please Fix this

**Comment by zientix** [comment]
U didnt import https://github.com/The-SourceCode/Discord.js-Bot-Development/blob/master/Ep_14/functions.js file in the kick.js and ban.js
