### ISSUE TITLE
episode 4 is online but when i write command....

### ISSUE THREAD

**Issue by TomClv** [The-SourceCode/Discord.js-Bot-Development#48]
(node:3056) UnhandledPromiseRejectionWarning: ReferenceError: arg is not defined
    at Client.<anonymous> (/Users/studio_1/Desktop/discorbots/ban/index.js:37:17)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/Users/studio_1/Desktop/discorbots/ban/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/Users/studio_1/Desktop/discorbots/ban/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/Users/studio_1/Desktop/discorbots/ban/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/Users/studio_1/Desktop/discorbots/ban/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/Users/studio_1/Desktop/discorbots/ban/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/Users/studio_1/Desktop/discorbots/ban/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/Users/studio_1/Desktop/discorbots/ban/node_modules/ws/lib/websocket.js:801:20)
(node:3056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by PantheraRed** [comment]
May you show some code or any sort of reference (screenshot) for us to understand better?
